### ISSUE TITLE
Humidity

### ISSUE THREAD

**Issue by iFac3** [biemond/com.athom.philipsair#1]
Hi biemond,

First of all I’d like to thank you so much this Homey app! 

What I experienced is regards to Humidity. The device shows target humidity instead of measured humidity. I can not access the integrated humidity sensor data even from insights, however would be awesome to set up automations based on this.

![EC2DFE03-497D-471C-817C-0B03D5C7F97E](https://user-images.githubusercontent.com/51527573/70271045-ea874e00-17a5-11ea-9a57-e77edbb71d1d.jpeg)

Other thing is connected to HomeKit Experiment. Philips device appears as a switch instead of purifier/humidifier and shows in the details target instead of current humidity.

My device is 3000i 2 in 1 Purifier and Humidifier (AC3829/10)

**Comment by biemond** [comment]
Hi,
Indeed I see this
https://github.com/rgerganov/py-air-control/blob/master/pyairctrl/airctrl.py#L146-L151

and totally missed it, let me fix it now.

about the switch, I use climate as app https://github.com/biemond/com.athom.philipsair/blob/master/app.json#L20
and device is other 
https://github.com/biemond/com.athom.philipsair/blob/master/app.json#L376
I can use 

Fan | fan | Use this device class for fans that cool your home. 
Heater | heater | Use this device class for heaters, that warm your home.

but that is also not correct.  I don't know how homekit is doing its translation.

thanks

**Comment by biemond** [comment]
done, submitted version 0.0.5 to athom or you can do homey app install from this repo.
for target you need to remove and add the device again.  plus you have now a humidity change trigger for your flows.

**Comment by iFac3** [comment]
Thanks a lot! 0.0.5 upgrade happened couple of days ago, since then works like a charm. But there is another bug what I can report you. When I readded device, after setting the right IP, Homey saved a not known IP first...

![IMG_4959](https://user-images.githubusercontent.com/51527573/70566697-dc19a780-1b94-11ea-9d40-0cd2b1fea0f2.jpeg)


...after editing it in settings, device started to report sensor data. The same happened first time with previous version and now with 0.0.5

Very look forward features like sleep/auto/allergen modes, light on/off, humidification on/off. 

Cheers! ;)

**Comment by biemond** [comment]
ok  hehe, thanks. this is my ip.  I will remove it and work on the new actions.

**Comment by iFac3** [comment]
Awesome! I’ll test it with joy!

**Comment by iFac3** [comment]
0.0.7 update is awesome! Only one thing I miss is the humidifier function on/off.

I hope actions will come soon. 😉

**Comment by biemond** [comment]
nice, I will try to add another device type which support purifier and humidifier. ( add the extra options) I cannot test them but I will take a look at it.

**Comment by iFac3** [comment]
I would test it with joy!

Rgds,

Gergely.

**Comment by biemond** [comment]
perfect, let me find out how this beta testing works on homey.

**Comment by biemond** [comment]
here we go https://homey.app/nl-nl/app/com.athom.philipsair/Philips-Air/test/
please try it out.
added new device and restrict the current one. 
you can set func  and target humidity . plus I show the water level ( don't know what it displays.)

**Comment by iFac3** [comment]
Hi Edwin,

Cool! Installed, tested.

Feedback:


• After install, similar issue to earlier versions with IP. After setting up and getting back to IP setup, IP address does not appear, however sensor reading works. If I type it again and save, it appears.
• Purification/Both switcher works
• Target Humidity switcher does not
• At readings, Water level shows “-“ (chk attachment) but as far as I know device only can show when it’s empty

So far so good! 😉


Rgds,

Gergely.

**Comment by iFac3** [comment]
Icon suggestions:

GAS: 
https://www.flaticon.com/free-icon/co2_1435182?term=co2%20pollution&page=1&position=3

Allergen index:
https://www.flaticon.com/free-icon/flower_2257463

Water level:
https://www.flaticon.com/free-icon/water-tank_2385748?term=water%20tank&page=1&position=69

**Comment by biemond** [comment]
thanks, I will work on those.

For Target Humidity switcher 
I don't know if you can install node on your pc /laptop.
but can you run test6.js from the com.athom.philipsair directory. like node test6.js

you have to change the ip to yours https://github.com/biemond/com.athom.philipsair/blob/master/test6.js#L12

Very curious about the below output, plus change the humidity target with all the possible values.
after that I can resolve it.  (maybe it is a number instead of a string)

```
statusCode: 200
{
  om: 's',
  pwr: '1',
  cl: false,
  aqil: 100,
  uil: '1',
  dt: 0,
  dtrs: 0,
  mode: 'P',
  pm25: 1,
  iaql: 1,
  aqit: 10,
  tvoc: 1,
  ddp: '1',
  rddp: '1',
  err: 0
}
```

**Comment by biemond** [comment]
Also very interested in this wink filter.

**Comment by biemond** [comment]
pushed a new test version with the advanced settings fix and the new icons.

**Comment by iFac3** [comment]
All fine! ThxAlot! Merry Christmas! (if you celebrate it)

Üdv,

G.

**Comment by iFac3** [comment]
Hi biemond,

I've run test6.js several times, output is in attachments.

[NoWater.txt](https://github.com/biemond/com.athom.philipsair/files/4008182/NoWater.txt) - Target Humidity 50% / Empty Water Tank
[FilledWater.txt](https://github.com/biemond/com.athom.philipsair/files/4008185/FilledWater.txt) - Target Humidity 50% / Full Water Tank
[Target40percent.txt](https://github.com/biemond/com.athom.philipsair/files/4008186/Target40percent.txt) - Target Humidity 40%
[Target60percent.txt](https://github.com/biemond/com.athom.philipsair/files/4008188/Target60percent.txt) - Target Humidity 60%
[TargetMaximum.txt](https://github.com/biemond/com.athom.philipsair/files/4008189/TargetMaximum.txt) - Target Humidity Maximum

Target Humidity states in Air Matters app:

![IMG_4CD6F8CB8F1B-1](https://user-images.githubusercontent.com/51527573/71559067-1a9ad780-2a5a-11ea-8d56-c20dabe06592.jpeg)


As water level decreases by the time, value of "wl" remains 100 till tank becomes empty, then changes to 0. So I think in Homey App, 100 should equals "OK" and 0 "Empty" in device's dashboard. (now it shows "-" all time if full or empty)

Other suggestions: In device switcher part:

![IMG_EEECDFB6567C-1](https://user-images.githubusercontent.com/51527573/71558911-6cdaf900-2a58-11ea-89ad-25a00604c4a5.jpeg)

"enabled" in titles is misleading at Display and Child lock since if related feature is switched off it shows enabled.

Humidifier function switching may also should be here, to be more clear with users.

**Comment by iFac3** [comment]
I haven't seen wick filter info in results of test6.js and since I have a Docker image installed with py-air-control I checked status of device and status of filters as well:

<img width="606" alt="Képernyőfotó 2019-12-29 - 17 21 33" src="https://user-images.githubusercontent.com/51527573/71559598-3bfec200-2a60-11ea-938f-ff59576ce0ab.png">

**Comment by biemond** [comment]
thanks. this helps.  can you do filter again with -d debug switch , I am curious if I see the response

**Comment by biemond** [comment]
actions
- "enabled" in titles is misleading at Display and Child lock 
- fix target humidity
- water level OK or empty.

Discussion
- Humidifier function switching, for now there are only 2 values, but this boolean control only allows on off. Are you saying we can just say  Humidifier on / off instead of purifier or both. I don't think philips will add some 3rd option like Humidifier only.

Todo
- wick filter

**Comment by iFac3** [comment]
I ran it with -d switch, seems nothing changed to me

[test6-d.txt](https://github.com/biemond/com.athom.philipsair/files/4008277/test6-d.txt)

**Comment by biemond** [comment]
ah cool, thanks.  I will add more debug on test6.js. I expect in the next 30 minutes a new testable version.

**Comment by iFac3** [comment]
Discussion

- Humidifier only mode is not possible since ventillation is needed for humidification so ventillated air can go through only HEPA and Active Carbon filter. 
- Connected only humidifier device is not available yet at Philips, question if it comes or not.

**Comment by biemond** [comment]
good, will do that.

**Comment by biemond** [comment]
and new version is here https://homey.app/a/com.athom.philipsair/test/ plus updated test6.js for more filter output.

**Comment by iFac3** [comment]
New things has appeared! Here you are: [NewResultsofTest6.txt](https://github.com/biemond/com.athom.philipsair/files/4008382/NewResultsofTest6.txt)

**Comment by biemond** [comment]
nice
```
{
  fltt1: 'A3',
  fltt2: 'C7',
  fltsts0: 278,
  fltsts1: 4325,
  fltsts2: 4325,
  wicksts: 4325
}
```

**Comment by iFac3** [comment]
Hmmmm... what fltt1&2 refer to?

Üdv,

G.

**Comment by biemond** [comment]
I think the type of filter which is used. it says something about the hepa and carbon filter type.

**Comment by iFac3** [comment]
New version has just been tested out. All features and readings (even water level) works fine except Humidifier switch. It does not at all.

Rgds,

Gergely.

**Comment by biemond** [comment]
you mean purifier or both or the target Humidity

**Comment by biemond** [comment]
I see the issue, fixing it now

**Comment by biemond** [comment]
pushed a new test version

**Comment by iFac3** [comment]
Everything is OK! 😃

Rgds,

Gergely.

**Comment by biemond** [comment]
awesome, will push it athom. thanks for all the testing.

**Comment by iFac3** [comment]
Thank you for your awesome work!

Rgds,

Gergely.

**Comment by biemond** [comment]
this is now live, now I will work on this wick filter

**Comment by iFac3** [comment]
Hi biemond,

Just wanted to say big thanks, I could manage to automate my Philips Air device wery well with the new flow abilities.

Once if you can spend some more time on this app, the light ring flow control would be the last missing thing from my perspective.


Cheers!

**Comment by biemond** [comment]
hehe too much light at night. 
will do. 

thanks

**Comment by iFac3** [comment]
You’rright! Thanks!

Btw, since last update I found something. Product code was missing, so I readded the device but after couple of hours it lost again the code.

![4D2CF0AB-9D0B-4DF5-AACB-B519535C139A](https://user-images.githubusercontent.com/51527573/75189247-133c3580-574e-11ea-86ac-6db456bae287.png)

**Comment by biemond** [comment]
oh, I think I got some error on getting the latest data. I am doing 3 steps , 1st get status, filters and firmware.  I think the last part goes wrong sometimes but I would expect it should be ok after a while.

Let me check this firmware part.

**Comment by biemond** [comment]
can you check this version. https://homey.app/nl-nl/app/com.athom.philipsair/Philips-Air/test/   .  I now reset the values between the polling plus show where the error occurs ( status, filter or firmware)

**Comment by iFac3** [comment]
Hi,

Two days passed with new version, no issues so far, moreover seems more accurate on status reporting.

Rgds,

G.

**Comment by biemond** [comment]
cool , will publish this version. maybe the error is still there on the philips device, at least 2 min later it will be refreshed by a new state

**Comment by iFac3** [comment]
Hi biemond!

It seems there is some issue since Homey 4.1.0... I lost control over my Philips Air device. It reads all data, but can not set any feature I had before so flows do not work anymore. I readded the device, it worked for a while but then lost the ability of control again.

**Comment by biemond** [comment]
ah , that is bad.  in the apps it works for me.  I will check the flows.

**Comment by biemond** [comment]
also action flows + triggers are working for me.  I was already using 4.1.0 or it RC version for the last 11 days.

**Comment by biemond** [comment]
maybe you can check your homey total memory or cpu power. https://developer.athom.com/tools/system or
https://developer.athom.com/tools/app-profiling 

are you using a lot of apps and flow. 
I got this

```
nodeVersion | "v8.16.0"
homeyVersion | "4.1.0"
homeyModelId | "homey3s"
homeyModelName | "Homey (Early 2019)"
```

**Comment by iFac3** [comment]
I guess no weakness on cpu or memory, since I have Pro version. I got this:

nodeVersion	"v8.16.0"
homeyVersion	"4.1.0"
homeyModelId	"homey3d"
homeyModelName	"Homey Pro (Early 2019)”


Shall I reinstall Philips Air app?

**Comment by iFac3** [comment]
I have this in under developer access:

[Philips status.xlsx](https://github.com/biemond/com.athom.philipsair/files/4408865/Philips.status.xlsx)

**Comment by iFac3** [comment]
I've played a bit with this recently, and found something.

Since I wrote you I've done reset device, reinstall app, readd device multiple times, but run into the same failure at some point. Everything goes well for a while, but once when issue comes, it has one visible thing every time:

![IMG_4979](https://user-images.githubusercontent.com/51527573/78961243-21bd9100-7af1-11ea-9376-bf8cc9f5fb0d.png)

Writes "Error on filter" at Product section.

Connecting result is that automated reporting stops, update on status happens only when I set anything on the device. (I can check it under "Latest update date") It's weird, becuase all started with lost control over the device, but now ability of control remains, however updating is missing.

**Comment by biemond** [comment]
Great info, let me check it again.  mostly a failure should not block the next run 2 minutes later.

**Comment by biemond** [comment]
also can you try if it has something to do with the wifi  connection and using 2.4ghz

**Comment by iFac3** [comment]
WiFi is definitely not an issue here, spectrum is clear, I have UniFi ac system, what works very good indeed.

Rgds,

Gergely.

**Comment by biemond** [comment]
oh wow , I have the same issue. error on filter  and last update from 2 days ago. plus control does not work.

**Comment by biemond** [comment]
restart app from the homey app works for me , nice I also got this issue

**Comment by iFac3** [comment]
It worked for me too now, I’m gonna check time by time and report you.

Rgds,

Gergely.

**Comment by biemond** [comment]
I see the errors in debug mode, status goes well , filter and firmware is failing.

**Comment by biemond** [comment]
found an error where there is a restart/ re-init of the app, 1st step went well but the old shared key was used on the 2 minute crontask .now I will always use the new key instead. 

can you test it again 
https://homey.app/a/com.athom.philipsair/test/

**Comment by biemond** [comment]
also I had to restart the philips device after too many retries , I was getting connection resets

**Comment by iFac3** [comment]
Is something changed in the Philips Air device behaviour, or Homey behavier differs?

Üdv,

G.

**Comment by biemond** [comment]
I think in homey

**Comment by iFac3** [comment]
I guessed... since the updated Homey FW...

Üdv,

G.

**Comment by biemond** [comment]
I hope philips auto updates its firmware, they changed protocol on late 2019 devices and I don't have 1 or I don't know how I can upgrade the firmware.

**Comment by biemond** [comment]
got it again after 4 hours,   Status is now 6 hours behind,  cron is still working. I see error on product. 
will try to find out why the key is not valid anymore and do some re-init when we got some failure

**Comment by biemond** [comment]
added a fix so secret is renewed after a communication error , plus store secret on device https://homey.app/a/com.athom.philipsair/test/

**Comment by iFac3** [comment]
Nice, thanks for update!

Test of 0.0.19 has just started...

...I’ll get back to you with feedback.

Rgds,

Gergely.

**Comment by biemond** [comment]
for me it is stable for the last 24 hours.  I don't know what is changed on homey or philips but it is good. I will retrieve/refresh its secret key on error at least so next time should be good again.
I saw somehow the key was not valid anymore. maybe we got some silence philips update.

**Comment by iFac3** [comment]
Hi Edvin,

Worked fine till now. The device has just became unreachable by Homey.



(IP exists, it has been fixed, device is reachable through the AirMatters app.

Rgds,

Gergely.

**Comment by iFac3** [comment]
A restart solved this, I'm testing continuously

**Comment by iFac3** [comment]
Allright! App is perfect again!
